grails-app/domain/subscriberpoc/User.groovy
package subscriberpoc

class User {

	transient springSecurityService

	String username
	String password
	boolean enabled
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
    String email
    Date lastPwdChange
    String[] pwdHistory = ['one','two','three','four','five','six','seven','eight']



	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password nullable: true, validator: {passwd, user ->
			passwd != user.username
		}
        email email: true, unique: true
        lastPwdChange nullable: true
        pwdHistory nullable: true

	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails-app/controllers/subscriberpoc/UserController.groovy
package subscriberpoc

import grails.plugin.springsecurity.annotation.Secured
import org.apache.commons.logging.LogFactory

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Secured(['ROLE_ADMIN'])
@Transactional(readOnly = true)
class UserController {

    private static final log = LogFactory.getLog(this)
    def springSecurityService
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def registerService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model: [userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        params.enabled = false
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view: 'create'
            return
        }

        userInstance.pwdHistory = userInstance.pwdHistory.tail() + userInstance.password
        userInstance.passwordExpired = true

        log.debug("User [" + springSecurityService.principal.username + "] creating user [" + userInstance.email + "]")
        userInstance.save flush: true
        UserRole.create userInstance, Role.findById(1), true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
        registerService.sendRegEmail(userInstance.email)

    }



    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view: 'edit'
            return
        }

        log.debug("User [" + springSecurityService.principal.username + "] updating user [" + userInstance.email + "]")
        userInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }
        UserRole userRole = UserRole.findByUser(userInstance)
        userRole*.delete();

        log.debug("User [" + springSecurityService.principal.username + "] deleting user [" + userInstance.email + "]")
        userInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }

}

grails-app/views/user/_form.gsp
<%@ page import="subscriberpoc.User" %>

<div class="row">
	<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
		<div class="col-md-2">
			<label for="username">
				<g:message code="user.username.label" default="Username" />
				<span class="required-indicator">*</span>
			</label>
		</div>
		<div class="col-md-10">
			<g:textField name="username" size="100" required="" value="${userInstance?.username}"/>
		</div>
	</div>
</div>
%{--<div class="row">--}%
	%{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">--}%
		%{--<div class="col-md-2">--}%
			%{--<label for="password">--}%
				%{--<g:message code="user.password.label" default="Password" />--}%
				%{--<span class="required-indicator">*</span>--}%
			%{--</label>--}%
		%{--</div>--}%
		%{--<div class="col-md-10">--}%
			%{--<g:textField name="password" size="100" required="" value="${userInstance?.password}"/>--}%
		%{--</div>--}%
	%{--</div>--}%
%{--</div>--}%
<div class="row">
	<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'email', 'error')} required">
		<div class="col-md-2">
			<label for="email">
				<g:message code="user.email.label" default="Email" />
				<span class="required-indicator">*</span>
			</label>
		</div>
		<div class="col-md-10">
			<g:field type="email" name="email" size="100" required="" value="${userInstance?.email}"/>
		</div>
	</div>
</div>
%{--<div class="row">--}%
	%{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'accountExpired', 'error')} ">--}%
		%{--<div class="col-md-2">--}%
			%{--<label for="accountExpired">--}%
				%{--<g:message code="user.accountExpired.label" default="Account Expired" />--}%
			%{--</label>--}%
		%{--</div>--}%
		%{--<div class="col-md-10">--}%
			%{--<g:checkBox name="accountExpired" value="${userInstance?.accountExpired}" />--}%
		%{--</div>--}%
	%{--</div>--}%
%{--</div>--}%
%{--<div class="row">--}%
	%{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'accountLocked', 'error')} ">--}%
		%{--<div class="col-md-2">--}%
			%{--<label for="accountLocked">--}%
				%{--<g:message code="user.accountLocked.label" default="Account Locked" />--}%
			%{--</label>--}%
		%{--</div>--}%
		%{--<div class="col-md-10">--}%
			%{--<g:checkBox name="accountLocked" value="${userInstance?.accountLocked}" />--}%
		%{--</div>--}%
	%{--</div>--}%
%{--</div>--}%
%{--<div class="row">--}%
	%{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'enabled', 'error')} ">--}%
		%{--<div class="col-md-2">--}%
			%{--<label for="enabled">--}%
				%{--<g:message code="user.enabled.label" default="Enabled" />--}%
			%{--</label>--}%
		%{--</div>--}%
		%{--<div class="col-md-10">--}%
			%{--<g:checkBox name="enabled" value="${userInstance?.enabled}" />--}%
		%{--</div>--}%
	%{--</div>--}%
%{--</div>--}%
%{--<div class="row">--}%
	%{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'passwordExpired', 'error')} ">--}%
		%{--<div class="col-md-2">--}%
			%{--<label for="passwordExpired">--}%
				%{--<g:message code="user.passwordExpired.label" default="Password Expired" />--}%
			%{--</label>--}%
		%{--</div>--}%
		%{--<div class="col-md-10">--}%
			%{--<g:checkBox name="passwordExpired" value="${userInstance?.passwordExpired}" />--}%
		%{--</div>--}%
	%{--</div>--}%
%{--</div>--}%

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
	<title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<body>
<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
	</ul>
</div>
<div id="create-user" class="content scaffold-create" role="main">
	<h1><g:message code="default.create.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<g:hasErrors bean="${userInstance}">
		<ul class="errors" role="alert">
			<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
			</g:eachError>
		</ul>
	</g:hasErrors>
	<g:form url="[resource:userInstance, action:'save']" >
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<fieldset class="buttons">
			<g:link controller="user" action="cancel">Cancel</g:link>
			<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
		</fieldset>
	</g:form>
</div>
</body>
</html>

grails-app/views/user/edit.gsp
<%@ page import="subscriberpoc.User" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
	<title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>
<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
		<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
	</ul>
</div>
<div id="edit-user" class="content scaffold-edit" role="main">
	<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<g:hasErrors bean="${userInstance}">
		<ul class="errors" role="alert">
			<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
			</g:eachError>
		</ul>
	</g:hasErrors>
	<g:form url="[resource:userInstance, action:'update']" method="PUT" >
		<g:hiddenField name="version" value="${userInstance?.version}" />
		<fieldset class="form">
			<g:render template="form"/>
		</fieldset>
		<fieldset class="buttons">
			<g:link controller="user" action="cancel">Cancel</g:link>
			<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
		</fieldset>
	</g:form>
</div>
</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="subscriberpoc.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="username" title="${message(code: 'user.username.label', default: 'Username')}" />
					
						<g:sortableColumn property="email" title="${message(code: 'user.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="accountExpired" title="${message(code: 'user.accountExpired.label', default: 'Account Expired')}" />
					
						%{--<g:sortableColumn property="accountLocked" title="${message(code: 'user.accountLocked.label', default: 'Account Locked')}" />--}%
					%{----}%
						%{--<g:sortableColumn property="enabled" title="${message(code: 'user.enabled.label', default: 'Enabled')}" />--}%
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${userInstanceList}" status="i" var="userInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "username")}</g:link></td>
					
						<td>${fieldValue(bean: userInstance, field: "email")}</td>
					
						<td><g:formatBoolean boolean="${userInstance?.passwordExpired}" /></td>
					
						%{--<td><g:formatBoolean boolean="${userInstance.accountLocked}" /></td>--}%
					%{----}%
						%{--<td><g:formatBoolean boolean="${userInstance.enabled}" /></td>--}%
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<g:if test="${userInstanceCount > 10}">
				<div class="pagination">
					<g:paginate total="${userInstanceCount ?: 0}" />
				</div>
			</g:if>
		</div>
	</body>
</html>

grails-app/views/user/show.gsp
<%@ page import="subscriberpoc.User" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="main">
	<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>
<body>
<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
	<ul>
		<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
		<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
		<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
	</ul>
</div>
<div id="show-user" class="content scaffold-show" role="main">
	<h1><g:message code="default.show.label" args="[entityName]" /></h1>
	<g:if test="${flash.message}">
		<div class="message" role="status">${flash.message}</div>
	</g:if>
	<ol class="property-list user">

		<g:if test="${userInstance?.username}">
			<li class="fieldcontain">
				<span id="username-label" class="property-label"><g:message code="user.username.label" default="UserName" /></span>

				<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${userInstance}" field="username"/></span>

			</li>
		</g:if>

		<g:if test="${userInstance?.email}">
			<li class="fieldcontain">
				<span id="email-label" class="property-label"><g:message code="user.email.label" default="Email" /></span>

				<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${userInstance}" field="email"/></span>

			</li>
		</g:if>



	</ol>
	<g:form url="[resource:userInstance, action:'delete']" method="DELETE">
		<fieldset class="buttons">
			%{--<g:link class="edit" action="edit" resource="${userInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>--}%
			<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
		</fieldset>
	</g:form>
</div>
</body>
</html>