grails-app/domain/subscriberpoc/Subscriber.groovy
package subscriberpoc

class Subscriber {

    String email
    String confirmCode
    boolean verified
    Boolean accepted
    Date dateCreated
    Date lastUpdated

    static hasMany = [topics: Topic]

    static constraints = {
        email email:true, unique: true
        confirmCode nullable: true
        accepted nullable: false
        topics nullable: false
    }
}

grails-app/controllers/subscriberpoc/SubscriberController.groovy
package subscriberpoc

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import grails.util.Holders
import groovy.xml.MarkupBuilder
import org.apache.commons.logging.LogFactory
import org.codehaus.groovy.grails.web.mapping.LinkGenerator

import static org.springframework.http.HttpStatus.NO_CONTENT
import static org.springframework.http.HttpStatus.OK

@Transactional(readOnly = false)
class SubscriberController {


    private static final log = LogFactory.getLog(this)
    def mailService
    def LinkGenerator grailsLinkGenerator
    def springSecurityService
    def subscriberService


    def index() {
        log.debug("index, params:" + params)
        [subscriberInstance: new Subscriber(params)]

    }

    @Secured(['ROLE_ADMIN'])
    def list(Integer max) {
        log.debug("list")
        def subscribers = []
        params.max = (max == null) ? 500 : max
        params.sort = (params.sort == null) ? "email" : params.sort
        log.debug("params: " + params)
        subscribers = Subscriber.list(params)


        respond subscribers

    }

    def cancel() {
        log.debug("cancel")
        redirect(action: 'index')
    }


    def signup() {
        log.debug("signup")
        withForm {
            def subscriberInstance
            try {
                log.debug(params)
                def existingUser = Subscriber.findByEmail(params.email)
                if (existingUser != null) {
                    log.debug("User already exists")
                    if (!existingUser.verified) {
                        log.debug("User already exists and not verified")
                        existingUser.delete()
                        subscriberInstance = subscriberService.createSubscriber(params)
                    } else {
                        flash.message = "User already exists."
                        //redirect(action: "index", model: [subscriberInstance: subscriberInstance])
                    }
                } else {
                    subscriberInstance = subscriberService.createSubscriber(params)
                }


            } catch (SubscriberException se) {
                flash.message = se.message
                redirect(action: 'index')
            }

            if (subscriberInstance != null) {
                mailService.sendMail {
                    to subscriberInstance.email
                    subject "New Subscription Confirmation"
                    from Holders.config.mail.from
                    html g.render(template: "mailtemplate", model: [code: subscriberInstance.confirmCode, email: subscriberInstance.email])
                }

                render(view: "success", model: [subscriberInstance: subscriberInstance])
                redirect(action: "success")
            } else {
                if (params.accepted == null) {
                    flash.message = 'Please ensure you accept the Terms and Conditions.'
                } else if (params.topics == null) {
                    flash.message = 'Please ensure you select at least one Topic.'
                } else {
                    //flash.message = 'Please fix the errors below.'
                }
                redirect(action: "index", model: [subscriberInstance: subscriberInstance])
            }
        }.invalidToken {
            // bad request
            flash.message = 'Invalid Request'
            redirect(action: 'index')
        }
    }

    def success() {
        log.debug("success")
        flash.message = 'Your subscription is almost created. Please complete the process ' +
                'using the email we have now sent to your email address'
        render(view: 'index')


    }

    def confirm(String id, String email) {
        log.debug("confirm")
        Subscriber subscriberInstance = Subscriber.findByConfirmCode(id)
        if (!subscriberInstance) {
            render(view: "success", model: [message: 'Problem confirming account'])
            return
        }

        subscriberInstance.verified = true
        if (!subscriberInstance.save(flush: true)|| !subscriberInstance.email.equals(email)) {
            render(view: "success", model: [message: 'Problem activating account'])
            return
        }

        def writer = new StringWriter()  // html is written here by markup builder
        def markup = new MarkupBuilder(writer)  // the builder
        markup.html {
            head {
                title"Australian Government Media Release Service"
                style(type:'text/css', "body{padding:40px;font-family: \"Open Sans\",\"Lucida Sans\",Arial,Helvetica,sans-serif !important;}h1{color:#ca3632;font-weight:600;font-size:20px;}h2{color: #00002d;margin-bottom: 0.3em;margin-top: 1.5em;font-size:14px;}p.url{color: #16589c;}p.snippet{}")
            }
            body {
                h1"Australian Government Media Release Service"
                div"Thank you for subscribing to Media Release notifications."
                p {
                    mkp.yieldUnescaped("<br />")
                    p {
                        a(href: grailsLinkGenerator.link(absolute: true, controller: 'subscriber', action: 'modify', id: subscriberInstance.confirmCode) + "?email=" + subscriberInstance.email, "Modify your Subscription")
                    }
                    p {
                        a(href: grailsLinkGenerator.link(absolute: true, controller: 'subscriber', action: 'remove', id: subscriberInstance.confirmCode) + "?email=" + subscriberInstance.email, "Cancel your Subscription")
                    }
                    p {
                        a(href: grailsLinkGenerator.link(absolute: true, controller: 'subscriber', action: 'index'), "Create a new Subscription")
                    }
                }
                div {
                    h2"Your details are:"
                    p"Email: " + subscriberInstance.email
                }
                div {
                    p"You may view all the latest Media Releases by visiting "
                    a(href:grailsLinkGenerator.link(absolute: true, controller: 'mediaRelease', action: 'index'), grailsLinkGenerator.link(absolute: true, controller: 'mediaRelease', action: 'index'))
                    p""
                }
                div {
                    p {
                        mkp.yield "If you experience any difficulty or require assistance, please contact us at "
                        a(href: 'http://australia.gov.au/contact-us', "http://australia.gov.au/contact-us")
                        mkp.yield "."
                    }
                    p"The Government Media Release Service is provided by the Digital Transformation Agency. Please note that this service does not monitor the content of media releases, which remain the responsibility of the relevant authoring agency."
                    p"This media release service is brought to you by the Digital Transformation Agency through Australia.gov.au"
                }
            }
        }

        mailService.sendMail{
            to subscriberInstance.email
            from Holders.config.mail.from
            subject "Australian Government Media Releases [SEC=UNCLASSIFIED]"
            html writer.toString()
        }

        flash.message = 'Your subscription has been successfully activated'
        render(view: 'index')
    }

     def modify(String id, String email) {
         log.debug("modify")
             Subscriber subscriberInstance = Subscriber.findByConfirmCode(id)
             if (!subscriberInstance || !subscriberInstance.email.equals(email)) {
                 render(view: "success", model: [message: 'Problem accessing account'])
                 return
             }
             render(view: "manage_subscriber", model: [subscriberInstance: subscriberInstance, editing: true])
    }
    @Transactional
    def update(String id) {
        log.debug("update:id=" + id)

        Subscriber subscriberInstance = Subscriber.findByConfirmCode(id)
        log.debug("update:" + subscriberInstance)

        if (!subscriberInstance) {
          render(view: "success", model: [message: 'Problem accessing account'])
          return
        }

        withForm {
            def topicsById = Topic.getAll(params.get('topics'))
            subscriberInstance.topics = topicsById
            if (subscriberInstance == null) {
                notFound()
                return
            }

            if (subscriberInstance.isDirty('email')) {
                log.debug("User somehow tried to change their email, resetting it back to original value")
                subscriberInstance.email = subscriberInstance.getPersistentValue('email')
            }

            if (subscriberInstance.isDirty('accepted')) {
                log.debug("User somehow tried to change their accepted, resetting it back to original value")
                subscriberInstance.accepted = subscriberInstance.getPersistentValue('accepted')
            }

            if (subscriberInstance.hasErrors()) {
                respond subscriberInstance.errors, view: 'edit'
                return
            }

            subscriberInstance.save flush: true

            request.withFormat {
                form multipartForm {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'Subscriber.label', default: 'Subscriber'), subscriberInstance.confirmCode])
                    redirect(action: 'showSubscriber', id: subscriberInstance.confirmCode, params: [email: subscriberInstance.email])

                }
                '*' { respond subscriberInstance, [status: OK] }

            }
        }.invalidToken {
            // bad request
            flash.message = 'Invalid Request'
            redirect(action: 'index')
        }
    }

    @Secured(['ROLE_ADMIN'])
    def show(Subscriber subscriberInstance) {
        log.debug("show")
        respond subscriberInstance
    }

grails-app/views/subscriber/_form.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<g:set var="ausgovUrl" value="${grailsApplication.config.australia.gov.au.url}" />
<body>
<section>
	<div class="container">
		<div class="row">
			<div class="form-group fieldcontain ${hasErrors(bean: subscriberInstance, field: 'email', 'error')} required">
				<label for="email">
					<g:message code="subscriber.email.label" default="Email:"/><span class="required-indicator">*</span>
				</label>
				<g:if test="${editing != null && editing == true}">
					${subscriberInstance?.email}
				</g:if>
				<g:else>
					<g:field type="email" name="email" required="required" value="${subscriberInstance?.email}" size="50" />
				</g:else>
			</div>
		</div>
		<div class="row">
			<div class="form-group fieldcontain ${hasErrors(bean: subscriberInstance, field: 'dateCreated', 'error')} required">
				<label for="email">
					<g:message code="subscriber.dateCreated.label" default="Date Created:"/>
				</label>
				${subscriberInstance?.dateCreated}
			</div>
		</div>
		<g:if test="${editing == null || editing == false}">
			<div class="row">
				<div class="fieldcontain ${hasErrors(bean: subscriberInstance, field: 'accepted', 'error')} ">
					<g:checkBox name="accepted" value="${subscriberInstance?.accepted}" /> Do you accept the <a href="${ausgovUrl}/privacy" target="_blank">Terms and Conditions as outlined in the Privacy Policy</a>.
				</div>
			</div>
		</g:if>
		<div class="row">
			<div class="form-group fieldcontain ${hasErrors(bean: subscriberInstance, field: 'subscriptions', 'error')} ">
				<label for="subscriptions" style="width:100%">
					<g:message code="subscriber.subscriptions.label" default="Topics:"/>

				</label>
				<div class="col-md-10">
					<p class="col-md-10" style="padding-left:0px;padding-right:60px;">
						<label class="subscriberCreateBox col-md-10" style="width:100%">
							<g:set var="selectAll" value="${subscriberInstance != null && subscriberInstance.topics != null && subscriberInstance.topics.size() != subscriberpoc.Topic.all.size()}" />
							<g:checkBox id="selectAllCheckBox" name="all" value="Select all" checked="${!selectAll}" /> Select All
						</label>
					</p>
					<g:each in="${subscriberpoc.Topic.list(sort: "name")}" var="topic">
						<label class="subscriberCreateBox col-md-3">
							<g:if test="${subscriberInstance != null && subscriberInstance.topics != null && !subscriberInstance.topics.contains(topic)}">
								<g:checkBox id="" name="topics" value="${topic.id}" checked="${false}" title="${topic.description}" /> ${topic.name}
								<div class="subscriberDescription">${topic.description}</div>
							</g:if>
							<g:else>
								<g:checkBox id="" name="topics" value="${topic.id}" checked="${true}" title="${topic.description}" /> ${topic.name}
								<div class="subscriberDescription">${topic.description}</div>
							</g:else>
						</label>
					</g:each>
				</div>
			</div>
		</div>
	</div>
</section>
</body>

grails-app/views/subscriber/_index_form.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<g:set var="ausgovUrl" value="${grailsApplication.config.australia.gov.au.url}" />
<body>
<section>
    <div class="container">
        <div class="row">
            <div class="form-group fieldcontain ${hasErrors(bean: subscriberInstance, field: 'email', 'error')} required">
                <label for="email">
                    <g:message code="subscriber.email.label" default="Email:"/><span class="required-indicator">*</span>
                </label>
                <g:if test="${editing != null && editing == true}">
                    ${subscriberInstance?.email}
                </g:if>
                <g:else>
                    <g:field type="email" name="email" required="required" value="${subscriberInstance?.email}" size="50" />
                </g:else>
            </div>
        </div>
        <g:if test="${editing == null || editing == false}">
            <div class="row">
                <div class="fieldcontain ${hasErrors(bean: subscriberInstance, field: 'accepted', 'error')} ">
                    <g:checkBox name="accepted" value="${subscriberInstance?.accepted}" /> Do you accept the <a href="${ausgovUrl}/privacy" target="_blank">Terms and Conditions as outlined in the Privacy Policy</a>.
                </div>
            </div>
        </g:if>
        <div class="row">
            <div class="form-group fieldcontain ${hasErrors(bean: subscriberInstance, field: 'subscriptions', 'error')} ">
                <label for="subscriptions" style="width:100%">
                    <g:message code="subscriber.subscriptions.label" default="Topics:"/>

                </label>
                <div class="col-md-10">
                    <p class="col-md-10" style="padding-left:0px;padding-right:60px;">
                        <label class="subscriberCreateBox col-md-10" style="width:100%">
                            <g:set var="selectAll" value="${subscriberInstance != null && subscriberInstance.topics != null && subscriberInstance.topics.size() != subscriberpoc.Topic.all.size()}" />
                            <g:checkBox id="selectAllCheckBox" name="all" value="Select all" checked="${!selectAll}" /> Select All
                        </label>
                    </p>
                    <g:each in="${subscriberpoc.Topic.list(sort: "name")}" var="topic">
                            <label class="subscriberCreateBox col-md-3">
                                <g:if test="${subscriberInstance != null && subscriberInstance.topics != null && !subscriberInstance.topics.contains(topic)}">
                                    <g:checkBox id="" name="topics" value="${topic.id}" checked="${false}" title="${topic.description}" /> ${topic.name}
                                    <div class="subscriberDescription">${topic.description}</div>
                                </g:if>
                                <g:else>
                                    <g:checkBox id="" name="topics" value="${topic.id}" checked="${true}" title="${topic.description}" /> ${topic.name}
                                    <div class="subscriberDescription">${topic.description}</div>
                                </g:else>
                            </label>
                    </g:each>
                </div>
            </div>
        </div>
    </div>
</section>
</body>

grails-app/views/subscriber/_mailtemplate.gsp
<%@ page contentType="text/html"%>
<head>
    <style type="text/css">
    body{padding:40px;font-family: "Open Sans","Lucida Sans",Arial,Helvetica,sans-serif !important;}h1{color:#ca3632;font-weight:600;}h2{color: #00002d;margin-bottom: 0.3em;margin-top: 1.5em;}p.url{color: #16589c;}p.snippet{}
    </style>
</head>
<div>
    <h1>Australian Government Email Subscription Confirmation</h1>

    <p>Please select the link below to confirm your subscription to Australian Government Media Release notifications. If you did not
subscribe you can ignore this email.</p>

    <a href='<g:createLink absolute="true" controller="subscriber" action="confirm" id="${code}" params="[email: email]" />'><g:createLink absolute="true" controller="subscriber" action="confirm" id="${code}" params="[email: email]" /></a>
</div>

grails-app/views/subscriber/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-subscriber" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subscriberInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subscriberInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}" encodeAs="html"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:subscriberInstance, action:'save']" useToken="true" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/subscriber/edit.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-subscriber" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${subscriberInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${subscriberInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}" encodeAs="html"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="${subscriberInstance.confirmCode}" method="PUT" useToken="true" >
				<g:hiddenField name="version" value="${subscriberInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/subscriber/index.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
<g:set var="ausgovUrl" value="${grailsApplication.config.australia.gov.au.url}" />
	<body class="not-front">
		<a href="#create-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="create-subscriber" class="content scaffold-create" role="main">
			<div class="col-md-4">
				<section class="sidebar clearfix panel-group" id="sidebar-first">
					<div class="region region-sidebar-first">
						<div class="block block-menu-block clearfix" id="block-menu-block-3">
							<div class="panel-heading">
								<h2>In this section</h2>
							</div>
							<div id="s1b-3" class="content panel-collapse collapse">
								<div class="panel-body">
									<div class="menu-block-wrapper menu-block-3 menu-name-main-menu parent-mlid-0 menu-level-3">
										<ul class="menu"><li class="first leaf menu-mlid-1146"><g:link uri="/mediaRelease">Latest media releases</g:link></li>
											<li class="leaf menu-mlid-1149"><a title="Media releases by portfolio" href="${ausgovUrl}/news-and-social-media/media-releases/media-releases-and-rss-feeds-by-portfolio">Media releases and RSS feeds by portfolio</a></li>
											<li class="last leaf menu-mlid-1147"><g:link uri="/subscriber">Subscribe to the Media Release Service</g:link></li>
										</ul></div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
			<div id="main-content" class="col-md-8" role="main">
				<h1>Subscribe for Media Release Notifications </h1>
				<g:if test="${flash.message}">
					<div class="message" role="status">${flash.message}</div>
				</g:if>


				<g:hasErrors bean="${subscriberInstance}">
					<ul class="errors" role="alert">
						<g:eachError bean="${subscriberInstance}" var="error">
							<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}" encodeAs="html"/></li>
						</g:eachError>
					</ul>
				</g:hasErrors>
				<g:form url="[resource:subscriberInstance, action:'signup']" useToken="true" >
					<fieldset class="form">
						<g:render template="index_form"/>
					</fieldset>
					<fieldset class="buttons">

						<g:submitButton name="Subscribe" class="btn btn-primary"
										value="${message(code: 'subscribe.button.create.label', default: 'Subscribe')}"/>
					</fieldset>
				</g:form>
			</div>
			</div>
		</div>
	</body>
</html>

grails-app/views/subscriber/list.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-subscriber" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="email" title="${message(code: 'subscriber.email.label', default: 'Email')}" />
					
						<g:sortableColumn property="verified" title="${message(code: 'subscriber.verified.label', default: 'Verified')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${subscriberInstanceList}" status="i" var="subscriberInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${subscriberInstance.id}">${fieldValue(bean: subscriberInstance, field: "email")}</g:link></td>
					
						<td><g:formatBoolean boolean="${subscriberInstance.verified}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>

				<div class="pagination">
					<g:paginate total="${subscriberInstanceList.getTotalCount()}" max="500" />
				</div>

		</div>
	</body>
</html>

grails-app/views/subscriber/manage_subscriber.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
    <title><g:message code="default.create.label" args="[entityName]" /></title>
</head>
<g:set var="ausgovUrl" value="${grailsApplication.config.australia.gov.au.url}" />
<body class="not-front">
<a href="#edit-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

<div id="edit-subscriber" class="content scaffold-create" role="main">
    <div class="col-md-4">
        <section class="sidebar clearfix panel-group" id="sidebar-first">
            <div class="region region-sidebar-first">
                <div class="block block-menu-block clearfix" id="block-menu-block-3">
                    <div class="panel-heading">
                        <h2>In this section</h2>
                    </div>
                    <div id="s1b-3" class="content panel-collapse collapse">
                        <div class="panel-body">
                            <div class="menu-block-wrapper menu-block-3 menu-name-main-menu parent-mlid-0 menu-level-3">
                                <ul class="menu"><li class="first leaf menu-mlid-1146"><g:link uri="/mediaRelease">Latest media releases</g:link></li>
                                    <li class="leaf menu-mlid-1149"><a title="Media releases by portfolio" href="${ausgovUrl}/news-and-social-media/media-releases/media-releases-and-rss-feeds-by-portfolio">Media releases and RSS feeds by portfolio</a></li>
                                    <li class="last leaf menu-mlid-1147"><g:link uri="/subscriber">Subscribe to the Media Release Service</g:link></li>
                                </ul></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <div id="main-content" class="col-md-8" role="main">
        <h1>Update My Media Release Subscription</h1>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
        <g:hasErrors bean="${subscriberInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${subscriberInstance}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}" encodeAs="html"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>


        <g:form url="${subscriberInstance.confirmCode}" method="POST" useToken="true" >
            <g:hiddenField name="version" value="${subscriberInstance?.version}" />
            <g:hiddenField name="accepted" value="${subscriberInstance?.accepted}" />
            <fieldset class="form">
                <g:render template="form"/>
            </fieldset>
            <fieldset class="buttons">
                <g:actionSubmit class="Update" action="update" value="${message (code: 'default.button.update.label', default: 'Update')}" />
                <g:actionSubmit class="remove" action="remove"  id="${subscriberInstance.confirmCode}" value="${message(code: 'default.button.delete.label', default: 'Unsubscribe')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
            </fieldset>
        </g:form>
    </div>
</div>
</div>
</body>
</html>

grails-app/views/subscriber/subscriber.gsp
<%@ page import="subscriberpoc.Subscriber" %>
<!DOCTYPE html>
<html>
<head>
    Show
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'subscriber.label', default: 'Subscriber')}" />
    <title><g:message code="default.edit.label" args="[entityName]" /></title>
</head>
<body>Subscriber
<a href="#edit-subscriber" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
    </ul>
</div>
<div id="edit-subscriber" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${subscriberInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${subscriberInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}" encodeAs="html"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="${subscriberInstance.id}" action="showSubscriber" method="POST" useToken="true" >
        <g:hiddenField name="version" value="${subscriberInstance?.version}" />
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="Update" action="update" value="${message (code: 'default.button.update.label', default: 'Update')}" />
            <g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
        </fieldset>
    </g:form>
</div>
</body>
</html>